name: Deploy Django to EC2 Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/projects/mcq

            echo ">>> Pulling latest code"
            git reset --hard
            git pull origin main

            echo ">>> Activating virtual environment"
            source venv/bin/activate

            echo ">>> Installing dependencies"
            pip install -r requirements.txt

            echo ">>> Running migrations"
            python manage.py migrate --noinput

            echo ">>> Collecting static"
            python manage.py collectstatic --noinput

            echo ">>> Restarting services"
            sudo systemctl restart gunicorn_mcq
            sudo systemctl reload nginx

            echo ">>> Deployment Completed Successfully"
